---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH

    #  untuk export DEPLOYPATH=/home/user/public_html/
    # user = nama dari yang didapatkan dari pembelian web hosting